### ISSUE TITLE
Generate Synthetic Boxes/Bags Data

### ISSUE THREAD

**Issue by lmtoan** [havanagrawal/clomask#19]
Generate boxes/bags masks on empty fridge/shelf to train a Mask-RCNN custom model

**Comment by lmtoan** [comment]
@tejasmhos 

I think you can go ahead and write an experimental script to place a single box/bag crop on an empty bag/shelf. Link this issue so the group can comment.

About mass generating artificial masks, we might have to thoroughly discuss the evaluation notebook before knowing which box/bag masks to generate.

**Comment by tejasmhos** [comment]
Deliverable: Multiple synthetic images comprised of a shelf with boxes superimposed on the shelf. Needs to account for different size of boxes and ensure that the images are as realistic as possible.

**Comment by tejasmhos** [comment]
I've currently collected a number of images of rigid boxes online, and have preprocessed them in Photoshop to remove backgrounds (didn't find alpha channel boxes as readily as bottles). Currently waiting for generalized synthetic generation script that Vishnu is working on to perform superimposition, resizing and scaling. Task should be closed soon after script is complete.

**Comment by tejasmhos** [comment]
Some additional assets were collected by Toan and I for the synthetic generation and evaluation of model on rigid objects. Pictures of rigid objects were taken at Target, along with an empty shelf to aid with synthetic generation. All assets are contained in the folder "Data-1229" under "data" folder. Additionally, rigid boxes with alpha channel are in the folder titled "food_boxes" in the "data" folder.

**Comment by havanagrawal** [comment]
Initially fixed by #23 , enhanced in #31
